# Basic Settings
locale: en-US
timezone: Asia/Hong_Kong

# Theme Settings
theme: academicpages
remote_theme: academicpages/academicpages.github.io

# Site Settings
title: "Junteng Liu"
name: "Junteng Liu"
description: "Personal website of Junteng Liu, first-year PhD candidate at HKUST NLP Group."
url: "https://giomerlins-ci.github.io"
baseurl: "/LJT-Homepage"
repository: "giomerlins-ci/LJT-Homepage"

# Teaser teaser
teaser: #/assets/images/vanilla-banner.png

# Logo of the website
logo: # /assets/images/avatar.png

)

# Search
search: true

# Analytics
analytics:
  provider: ""
  google:
    tracking_id: ""
    anonymize_ip: true

# Comments
comments:
  provider: ""
  disqus:
    shortname: ""

# Pagination
paginate: 5
paginate_path: /page:num/

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Vicent0205"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/junteng88716710"

# Author Profile
author:
  name: "Junteng Liu"
  avatar: "/assets/images/avatar.png"
  bio: "First-year PhD candidate at HKUST NLP Group."
  location: "Hong Kong"
  email: "jliugi@connect.ust.hk"
  google-scholar: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
  github: "Vicent0205"
  twitter: "junteng88716710"

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author_profile: true
      read_time: true
      comments: true
  - scope:
      path: "" 
      type: "publications"
    values:
      layout: "single"
      author_profile: true
  - scope:
      path: ""
      type: "talks"
    values:
      layout: "single"
      author_profile: true
  - scope:
      path: ""
      type: "teaching"
    values:
      layout: "single"
      author_profile: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# Conversion
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    disable: true

# Output
permalink: /:categories/:title/

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Makefile
  - README.md
  - "*.json"
  - "*.py"
  - "*.ipynb"
  - Dockerfile
  - docker-compose.yaml
  - .devcontainer/
  - .github/
  - scripts/
  - markdown_generator/
  - files/